steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/lp-labs-pubsub/labs.pubsub.email', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/lp-labs-pubsub/labs.pubsub.email']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'labs-pubsub-email', '--image', 'gcr.io/lp-labs-pubsub/labs.pubsub.email', '--region', 'us-central1']
images:
- gcr.io/lp-labs-pubsub/labs.pubsub.email